export const shakespeareQuotes = [
  "Virginity breeds mites, much like a cheese.",
  "I do desire we may be better strangers.",
  "I must to the barber's, monsieur; for methinks, I am marvellous hairy about the face: and I am such a tender ass, if my hair do but tickle me, I must scratch.",
  "Mine eyes smell onions; I shall weep anon.",
  "There live not three good men unhanged in England; and one of them is fat and grows old.",
  "You starveling, you elf-skin, you dried neat's tongue, you bull's pizzle, you stock-fish!",
  "Lord, what fools these mortals be!",
  "The lady doth protest too much, methinks.",
  "Though this be madness, yet there is method in't.",
  "Brevity is the soul of wit.",
  "What's in a name? That which we call a rose by any other name would smell as sweet.",
  "All the world's a stage, and all the men and women merely players.",
  "To thine own self be true.",
  "The course of true love never did run smooth.",
  "Some are born great, some achieve greatness, and some have greatness thrust upon them.",
  "Away, you starvelling, you elf-skin, you dried neat's-tongue, bull's-pizzle, you stock-fish!",
  "More of your conversation would infect my brain.",
  "Thine face is not worth sunburning.",
  "Thou art a boil, a plague-sore, an embossed carbuncle in my corrupted blood.",
  "You Banbury cheese!",
  "Thou sodden-witted lord! Thou hast no more brain than I have in mine elbows.",
  "He has not so much brain as ear-wax.",
  "Your brain is as dry as the remainder biscuit after voyage.",
  "There's small choice in rotten apples.",
  "Thou whoreson zed! Thou unnecessary letter!",
  "Villain, I have done thy mother.",
  "Neighbors, you are tedious.",
  "Would thou wert clean enough to spit upon!",
  "Observe him, for the love of mockery.",
  "You are not worth another word, else I'd call you knave.",
  "I do bite my thumb, sir.",
  "Away thou rag, thou quantity, thou remnant.",
  "There's no more faith in thee than in a stewed prune.",
  "O villain! Thou wilt be condemned into everlasting redemption for this.",
  "Marry, sir, they have committed false report; moreover, they have spoken untruths; secondarily, they are slanders; sixth and lastly, they have belied a lady; thirdly, they have verified unjust things; and, to conclude, they are lying knaves."
];